[package]
name = "rumble"
version = "0.0.0"
authors = ["timokoesters", "Alexander Dmitriev", "Frederick Gnodtke <frederick@gnodtke.net>"]
edition = "2018"

[dependencies]
openssl = "*"
protobuf = "*"
byteorder = "*"
