[package]
name = "rumble"
version = "0.0.0"
authors = ["Alexander Dmitriev", "Frederick Gnodtke <frederick@gnodtke.net>"]

[lib]
name = "rumble"
path = "src/lib.rs"
test = true
doc = true

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl.git"
features = ["tlsv1_2", "tlsv1_1"]
