[package]
name = "rumble"
version = "0.0.0"
authors = ["Alexander Dmitriev", "Frederick Gnodtke <frederick@gnodtke.net>"]

[lib]
name = "rumble"
path = "src/lib.rs"
test = true
doc = true

[dependencies]
openssl = "*"
